### ISSUE TITLE
不支持多线程并发执行，cuda 版本我看是可以的

### ISSUE THREAD

**Issue by junior-zsy** [Ascend/pytorch#13]
代码： 
rom transformers import AutoTokenizer, AutoModel
import time
import threading

def chat_in_thread(tokenizer, model, i):
    start_time = time.time()
    response, history = model.chat(tokenizer, "你是谁开发的", history=[])
    end_time = time.time()
    print(f"Thread {i}: Response - {response}")
    print(f"Thread {i}: Execution time - {end_time - start_time} seconds")

# 加载模型前的开始时间
start_time = time.time()

tokenizer = AutoTokenizer.from_pretrained("/home/jovyan/fast-data/chatglm3-6b-32k", trust_remote_code=True)
model = AutoModel.from_pretrained("/home/jovyan/fast-data/chatglm3-6b-32k", trust_remote_code=True).half().npu()

# 计算加载模型的时间
model_load_time = time.time() - start_time

# 创建多个线程执行聊天功能
threads = []
num_threads = 4

for i in range(num_threads):
    thread = threading.Thread(target=chat_in_thread, args=(tokenizer, model, i))
    threads.append(thread)

# 启动线程
for thread in threads:
    thread.start()

# 等待所有线程完成
for thread in threads:
    thread.join()

print("Model loading time:", model_load_time, "seconds")

报错信息： 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/jovyan/fast-data/conda/envs/py/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/jovyan/fast-data/conda/envs/py/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jovyan/fast-data/mul_python.py", line 7, in chat_in_thread
    response, history = model.chat(tokenizer, "你是谁开发的", history=[])
  File "/home/jovyan/fast-data/conda/envs/py/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/chatglm3-6b-32k/modeling_chatglm.py", line 1034, in chat
    inputs = inputs.to(self.device)
  File "/home/jovyan/fast-data/conda/envs/py/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 772, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/jovyan/fast-data/conda/envs/py/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 772, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
RuntimeError: allocate:/usr1/02/workspace/j_ywhtRpPk/pytorch/torch_npu/csrc/core/npu/NPUCachingAllocator.cpp:1406 NPU error, error code is 107002
[Error]: The context is empty.
        Check whether acl.rt.set_context or acl.rt.set_device is called.
EE1001: The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]
        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
        TraceBack (most recent call last):
        ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4290]
        The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]

**Comment by sunchuhan-930** [comment]
尝试更新驱动试试

**Comment by Coloured-glaze** [comment]
你好，你的问题解决了吗

**Comment by strike20023** [comment]
这个是显卡的一些信息：
$npu-smi info
+------------------------------------------------------------------------------------------------+
| npu-smi 23.0.rc2                 Version: 23.0.rc2                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 1     910PremiumA         | OK            | 84.3        40                0    / 0             |
| 0                         | 0000:81:00.0  | 0           1901 / 15137      1    / 32768         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
我尝试使用torch_npu
python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 04:25:25) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch, torch_npu
>>> torch.rand(1).to('npu')*2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: getDevice:/usr1/02/workspace/j_vqN6BFvg/pytorch/torch_npu/csrc/core/npu/impl/NPUGuardImpl.h:42 NPU error, error code is 107002
[Error]: The context is empty.
        Check whether acl.rt.set_context or acl.rt.set_device is called.
EE1001: The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]
        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
        TraceBack (most recent call last):
        ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:4290]
        The argument is invalid.Reason: rtGetDevMsg execute failed, reason=[context pointer null]

**Comment by junior-zsy** [comment]
更新到最新的驱动 也是不行的，这个我在 gitee 上面已经反馈过，也是说更新驱动，最后又说不支持，感觉开发人员都是敷衍的，自己根本不知道支持不支持，

**Comment by junior-zsy** [comment]
更新到最新的驱动 也是不行的，@sunchuhan-930  这个能确定是否支持呢 ，上面的模型是开源的 chatglm3-6b-32k，代码已经发了，你可以更新驱动试下，看看是否支持

**Comment by sunchuhan-930** [comment]
就是调rt接口前，需要调用rtsetdevice
可以看下社区的cann接口说明

**Comment by ChuBoning** [comment]
新起线程时需要设置该线程使用的npu设备，例如
```
import torch
import torch_npu
import threading

torch_npu.npu.set_device(0)
def _worker(
    i: int
) -> None:
    torch_npu.npu.set_device(0)
    a = torch.randn(2).npu()
    print(a)

threads = [threading.Thread(target=_worker,
                            args=(i,))
            for i in range(3)]

for thread in threads:
    thread.start()
for thread in threads:
    thread.join()
```
注：目前npu暂不支持多线程中使用和主线程不同的npu设备,即将在下个版本中支持

**Comment by junior-zsy** [comment]
@ChuBoning 单卡的话这样是可以的，如果一个模型 加载在 2 张卡上面  ，是需要 torch_npu.npu.set_device("0,1") 使用吗，谢谢

**Comment by ChuBoning** [comment]
> @ChuBoning 单卡的话这样是可以的，如果一个模型 加载在 2 张卡上面 ，是需要 torch_npu.npu.set_device("0,1") 使用吗，谢谢

多卡请使用DDP，例如
```
model_DDP = torch.nn.parallel.DistributedDataParallel(
            model_DDP, device_ids=npu_subset, gradient_as_bucket_view=bucket_view
        )
```

**Comment by junior-zsy** [comment]
@ChuBoning 我现在加载模型是用的  transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。

transformers库的使用大致是这样的:

model = AutoModelForCausalLM.from_pretrained(
    "chatglm3-6b-32k",
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)
model.chat(tokenizer, "你是谁开发的", history=[])

如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device  确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel  ，我需要自己实现 transformers 类似的推理 操作 。谢谢

**Comment by junior-zsy** [comment]
@ChuBoning 能帮我看一下上面的问题吗，谢谢

**Comment by junior-zsy** [comment]
@ChuBoning 能帮我看一下上面的问题吗，谢谢

**Comment by ChuBoning** [comment]
@Tyx-main 麻烦看下这个问题

> @ChuBoning 我现在加载模型是用的 transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。
> 
> transformers库的使用大致是这样的: // device_map 设置成auto 模型 会被 平均加载到多卡上面 ，推理的时候也自动使用多卡推理 model = AutoModelForCausalLM.from_pretrained( "chatglm3-6b-32k", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True ) model.chat(tokenizer, "你是谁开发的", history=[])
> 
> 如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device 确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel ，我需要自己实现 transformers 类似的推理操作吗 。谢谢

**Comment by Tyx-main** [comment]
> @Tyx-main 麻烦看下这个问题
> 
> > @ChuBoning 我现在加载模型是用的 transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。
> > transformers库的使用大致是这样的: // device_map 设置成auto 模型 会被 平均加载到多卡上面 ，推理的时候也自动使用多卡推理 model = AutoModelForCausalLM.from_pretrained( "chatglm3-6b-32k", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True ) model.chat(tokenizer, "你是谁开发的", history=[])
> > 如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device 确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel ，我需要自己实现 transformers 类似的推理操作吗 。谢谢

多卡DDP启动的方式可参考如下示例：
```
nohup python3 -m torch.distributed.run --nproc_per_node 8 run_clm.py \
    --model_name_or_path facebook/bart-base \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --overwrite_output_dir \
    --output_dir ./output > ${scripts_path_dir}/output/run_bart.log 2>&1 &
```

**Comment by Tyx-main** [comment]
> > @Tyx-main 麻烦看下这个问题
> > > @ChuBoning 我现在加载模型是用的 transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。
> > > transformers库的使用大致是这样的: // device_map 设置成auto 模型 会被 平均加载到多卡上面 ，推理的时候也自动使用多卡推理 model = AutoModelForCausalLM.from_pretrained( "chatglm3-6b-32k", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True ) model.chat(tokenizer, "你是谁开发的", history=[])
> > > 如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device 确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel ，我需要自己实现 transformers 类似的推理操作吗 。谢谢
> 
> 多卡DDP启动的方式可参考如下示例：
> 
> ```
> nohup python3 -m torch.distributed.run --nproc_per_node 8 run_clm.py \
>     --model_name_or_path facebook/bart-base \
>     --dataset_name wikitext \
>     --dataset_config_name wikitext-2-raw-v1 \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 8 \
>     --do_train \
>     --do_eval \
>     --overwrite_output_dir \
>     --output_dir ./output > ${scripts_path_dir}/output/run_bart.log 2>&1 &
> ```

@junior-zsy

**Comment by Tyx-main** [comment]
> @Tyx-main 麻烦看下这个问题
> 
> > @ChuBoning 我现在加载模型是用的 transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。
> > transformers库的使用大致是这样的: // device_map 设置成auto 模型 会被 平均加载到多卡上面 ，推理的时候也自动使用多卡推理 model = AutoModelForCausalLM.from_pretrained( "chatglm3-6b-32k", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True ) model.chat(tokenizer, "你是谁开发的", history=[])
> > 如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device 确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel ，我需要自己实现 transformers 类似的推理操作吗 。谢谢

多卡推理目前暂不支持。即将会支持多卡推理 device_map:auto

**Comment by Tyx-main** [comment]
> > @Tyx-main 麻烦看下这个问题
> > > @ChuBoning 我现在加载模型是用的 transformers 这个库来加载模型的，因为后面我要用 transformers 库里 封装好的 方法 来完成推理操作。
> > > transformers库的使用大致是这样的: // device_map 设置成auto 模型 会被 平均加载到多卡上面 ，推理的时候也自动使用多卡推理 model = AutoModelForCausalLM.from_pretrained( "chatglm3-6b-32k", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True ) model.chat(tokenizer, "你是谁开发的", history=[])
> > > 如果是单卡 ，我在 model.chat 加 torch_npu.npu.set_device 确实可以，如果是多卡，您说用 torch.nn.parallel.DistributedDataParallel 这种方式，我不清楚 如何跟 transformers 结合，使用 transformers 的推理，还是如果用 torch.nn.parallel.DistributedDataParallel ，我需要自己实现 transformers 类似的推理操作吗 。谢谢
> 
> 多卡推理目前暂不支持。即将会支持多卡推理 device_map:auto

@junior-zsy
